version: '3'

services:
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - jdbc-dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: treinamento
      POSTGRES_PASSWORD: treinamento
      POSTGRES_DB: treinamento

volumes:
  jdbc-dbdata:
    external: true
